

default_platform(:ios)

platform :ios do

  before_all do
    setup_ci
  end

  desc "Run unit and UI tests"
  lane :tests do
    scan(
      scheme: "MyApp",
      clean: true,
      devices: ["iPhone 15"]
    )
  end

  desc "Build app"
  lane :build do
    build_app(
      scheme: "MyApp",
      export_method: "app-store"
    )
  end

  desc "Upload to TestFlight"
  lane :beta do
    match(type: "appstore")
    increment_build_number
    build_app(scheme: "MyApp")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end

